"""BUILD definitions for cuda_nvfatbin package"""

# This BUILD file is used within the arch specific cuda redist repository.
#
# Any user-facing target should be listed in _REPO_PUBLIC_TARGETS so that the
# @cuda_nvfatbin proxy repository can re-export it.

load("@rules_cc//cc:cc_import.bzl", "cc_import")
load("@rules_cc//cc:cc_library.bzl", "cc_library")
load("//:version.bzl", "LIB_SONAME_VERSIONS", "LIB_VERSIONS")

cc_import(
    name = "nvfatbin_shared_library",
    deps = [":headers"],
    shared_library = "lib/libnvfatbin.so." + LIB_SONAME_VERSIONS["libnvfatbin"],
    visibility = ["//visibility:public"],
)

cc_import(
    name = "nvfatbin_static_library",
    deps = [":headers"],
    static_library = "lib/libnvfatbin_static.a",
)

cc_library(
    name = "nvfatbin",
    deps = [":nvfatbin_shared_library"],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "nvfatbin_static",
    deps = [":nvfatbin_static_library"],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "shared_library_files",
    srcs = [
        "lib/libnvfatbin.so." + LIB_VERSIONS["libnvfatbin"],
    ],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "header_list",
    srcs = [
        "include/nvFatbin.h",
    ],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "headers",
    hdrs = [":header_list"],
    includes = ["include"],
    strip_include_prefix = "include",
    visibility = ["//visibility:public"],
)
