load("@bazel_lib//:bzl_library.bzl", "bzl_library")
load(":nccl_redist_build_defs_test.bzl", "nccl_redist_build_defs_test_suite")

bzl_library(
    name = "nccl_redist_build_defs",
    srcs = ["nccl_redist_build_defs.bzl"],
    visibility = ["//visibility:public"],
    deps = [":nccl_redist_versions"],
)

bzl_library(
    name = "nccl_redist_versions",
    srcs = ["nccl_redist_versions.bzl"],
    visibility = ["//visibility:public"],
)

nccl_redist_build_defs_test_suite(
    name = "nccl_redist_build_defs_tests",
)
