load("@bazel_lib//:bzl_library.bzl", "bzl_library")
load(":nccl_redist_build_defs_test.bzl", "nccl_redist_build_defs_test_suite")

exports_files(
    [
        "update_redists.py",
        "update_redists_test.py",
    ],
    visibility = ["//tools/nccl:__pkg__"],
)

filegroup(
    name = "nccl_redist_versions_json",
    srcs = ["nccl_redist_versions.json"],
    visibility = ["//tools/nccl:__pkg__"],
)

bzl_library(
    name = "nccl_redist_build_defs",
    srcs = ["nccl_redist_build_defs.bzl"],
    visibility = ["//visibility:public"],
)

nccl_redist_build_defs_test_suite(
    name = "nccl_redist_build_defs_tests",
)
