"""Shared catalog for CUDA proxy package generation."""

REPO_PUBLIC_TARGETS = {
    "cuda_cccl": [
        "header_list",
        "headers",
        "thrust_header_list",
        "thrust_headers",
        "cuda_header_list",
        "cuda_headers",
        "nv_header_list",
        "nv_headers",
        "cub_header_list",
        "cub_headers",
    ],
    "cuda_compat": [
        "driver_shared_library",
        "driver_interface_library",
        "cuda_shared_library",
        "cuda_interface_library",
        "nvidia_driver",
        "nvidia_driver_system",
        "nvidia-ptxjitcompiler_shared_library",
        "nvidia-ptxjitcompiler_interface_library",
        "nvidia_ptxjitcompiler",
        "nvidia_ptxjitcompiler_system",
        "cudadebugger_shared_library",
        "cudadebugger_interface_library",
        "cudadebugger",
        "cudadebugger_system",
        "nvidia_nvvm_shared_library",
        "nvidia_nvvm_interface_library",
        "nvidia_nvvm",
        "nvidia_nvvm_system",
        "nvidia_nvvm70_shared_library",
        "nvidia_nvvm70_interface_library",
        "nvidia_nvvm70_system",
        "nvidia_gpucomp_shared_library",
        "nvidia_gpucomp_interface_library",
        "nvidia_gpucomp_system",
        "nvidia_tileiras_shared_library",
        "nvidia_tileiras_interface_library",
        "nvidia_tileiras_system",
        "shared_library_files",
    ],
    "cuda_crt": ["header_list", "headers"],
    "cuda_cublas": ["cublas_shared_library", "cublas_interface_library", "cublasLt_shared_library", "cublasLt_interface_library", "cublas", "cublas_system", "cublasLt", "cublasLt_system", "cublas_static", "cublasLt_static", "nvblas_shared_library", "nvblas_interface_library", "nvblas", "nvblas_system", "header_list", "headers", "shared_library_files"],
    "cuda_cudart": ["static", "cudadevrt_static", "cuda_stub", "cudart_shared_library", "cudart_interface_library", "cuda_driver", "cudart", "cudart_system", "header_list", "headers", "cuda_header", "cuda", "shared_library_files"],
    "cuda_cudnn": [
        "cudnn_ops_infer",
        "cudnn_cnn_infer",
        "cudnn_ops_train",
        "cudnn_cnn_train",
        "cudnn_adv_infer",
        "cudnn_adv_train",
        "cudnn_ops",
        "cudnn_cnn",
        "cudnn_adv",
        "cudnn_graph",
        "cudnn_engines_precompiled",
        "cudnn_engines_runtime_compiled",
        "cudnn_heuristic",
        "cudnn_main",
        "cudnn",
        "cudnn_ops_infer_static",
        "cudnn_cnn_infer_static",
        "cudnn_ops_train_static",
        "cudnn_cnn_train_static",
        "cudnn_adv_infer_static",
        "cudnn_adv_train_static",
        "cudnn_ops_static",
        "cudnn_cnn_static",
        "cudnn_adv_static",
        "cudnn_graph_static",
        "cudnn_engines_precompiled_static",
        "cudnn_engines_runtime_compiled_static",
        "cudnn_heuristic_static",
        "cudnn_static",
        "header_list",
        "headers",
    ],
    "cuda_culibos": ["culibos_static"],
    "cuda_cufft": ["cufft_shared_library", "cufft_interface_library", "cufft", "cufft_system", "cufft_static", "cufft_static_nocallback", "cufftw_shared_library", "cufftw_interface_library", "cufftw", "cufftw_system", "cufftw_static", "header_list", "headers", "shared_library_files"],
    "cuda_cupti": ["cupti_shared_library", "cupti_interface_library", "cupti", "cupti_system", "cupti_static", "checkpoint_shared_library", "checkpoint_interface_library", "checkpoint", "checkpoint_system", "nvperf_host_shared_library", "nvperf_host_interface_library", "nvperf_host", "nvperf_host_system", "nvperf_host_static", "nvperf_target_shared_library", "nvperf_target_interface_library", "nvperf_target", "nvperf_target_system", "pcsamplingutil_shared_library", "pcsamplingutil_interface_library", "pcsamplingutil", "pcsamplingutil_system", "header_list", "headers", "cuda_cupti", "shared_library_files"],
    "cuda_curand": ["curand_shared_library", "curand_interface_library", "curand", "curand_system", "curand_static", "header_list", "headers", "shared_library_files"],
    "cuda_cusolver": ["cusolver_shared_library", "cusolver_interface_library", "cusolver", "cusolver_system", "cusolverMg_shared_library", "cusolverMg_interface_library", "cusolverMg", "cusolverMg_system", "cusolver_static", "cusolver_lapack_static", "cusolver_metis_static", "metis_static", "header_list", "headers", "shared_library_files"],
    "cuda_cusparse": ["cusparse_shared_library", "cusparse_interface_library", "cusparse", "cusparse_system", "cusparse_static", "header_list", "headers", "shared_library_files"],
    "cuda_driver": [
        "driver_shared_library",
        "driver_interface_library",
        "nvidia-ptxjitcompiler_shared_library",
        "nvidia-ptxjitcompiler_interface_library",
        "cuda_shared_library",
        "cuda_interface_library",
        "nvidia_driver",
        "nvidia_driver_system",
        "nvidia_ptxjitcompiler",
        "nvidia_ptxjitcompiler_system",
        "cudadebugger_shared_library",
        "cudadebugger_interface_library",
        "cudadebugger_system",
        "nvidia_nvvm_shared_library",
        "nvidia_nvvm_interface_library",
        "nvidia_nvvm_system",
        "include_cuda_umd_libs",
        "cuda_umd_libs",
        "shared_library_files",
    ],
    "cuda_nccl": [
        "nccl_shared_library",
        "nccl_static_library",
        "nccl",
        "nccl_static",
        "header_list",
        "headers",
        "shared_library_files",
    ],
    "cuda_nvcc": ["nvcc_directory", "libdevice", "nvlink", "fatbinary", "bin2c", "ptxas", "nvcc", "cudafe", "nvcc_profile", "prelink_stub", "nvcc_device_query", "bin", "link_stub", "header_list", "headers", "cuda_nvcc", "nvptxcompiler"],
    "cuda_nvdisasm": ["nvdisasm"],
    "cuda_nvfatbin": ["nvfatbin_shared_library", "nvfatbin_static_library", "nvfatbin", "nvfatbin_static", "header_list", "headers", "shared_library_files"],
    "cuda_nvjitlink": ["nvjitlink_shared_library", "nvjitlink_interface_library", "nvjitlink", "nvjitlink_system", "nvjitlink_static", "header_list", "headers", "shared_library_files"],
    "cuda_nvml": ["header_list", "headers", "nvidia-ml_stub", "nvidia_ml_static_stub", "nvml"],
    "cuda_nvptxcompiler": ["header_list", "headers", "nvptxcompiler_static", "nvptxcompiler"],
    "cuda_nvprune": ["nvprune"],
    "cuda_nvrtc": ["nvrtc_main", "nvrtc_builtins_shared_library", "nvrtc_builtins_interface_library", "nvrtc_builtins", "nvrtc_builtins_system", "nvrtc", "nvrtc_system", "nvrtc_static", "nvrtc_builtins_static", "nvrtc_stub", "header_list", "headers", "shared_library_files"],
    "cuda_nvtx": ["header_list", "headers", "shared_library_files"],
    "cuda_nvvm": ["cicc", "libdevice", "libnvvm", "nvptxcompiler"],
    "cuda_nvshmem": [
        "nvshmem_host_shared_library",
        "nvshmem_device_static_library",
        "nvshmem",
        "header_list",
        "headers",
        "shared_library_files",
    ],
    "cuda_profiler_api": ["header_list", "headers"],
}
