"""Shared catalog for CUDA proxy package generation."""

REPO_PUBLIC_TARGETS = {
    "cuda_cccl": [
        "header_list",
        "headers",
        "thrust_header_list",
        "thrust_headers",
        "cuda_header_list",
        "cuda_headers",
        "nv_header_list",
        "nv_headers",
        "cub_header_list",
        "cub_headers",
    ],
    "cuda_compat": [
        "driver_shared_library",
        "cuda_shared_library",
        "nvidia_driver",
        "nvidia-ptxjitcompiler_shared_library",
        "nvidia_ptxjitcompiler",
        "cudadebugger_shared_library",
        "cudadebugger",
        "nvidia_nvvm_shared_library",
        "nvidia_nvvm",
        "nvidia_nvvm70_shared_library",
        "nvidia_gpucomp_shared_library",
        "nvidia_tileiras_shared_library",
        "shared_library_files",
    ],
    "cuda_crt": ["header_list", "headers"],
    "cuda_cublas": ["cublas_shared_library", "cublasLt_shared_library", "cublas", "cublasLt", "cublas_static", "cublasLt_static", "nvblas_shared_library", "nvblas", "header_list", "headers", "shared_library_files"],
    "cuda_cudart": ["static", "cudadevrt_static", "cuda_stub", "cudart_shared_library", "cuda_driver", "cudart", "header_list", "headers", "cuda_header", "cuda", "shared_library_files"],
    "cuda_culibos": ["culibos_static"],
    "cuda_cufft": ["cufft_shared_library", "cufft", "cufft_static", "cufftw_shared_library", "cufftw", "cufftw_static", "header_list", "headers", "shared_library_files"],
    "cuda_cupti": ["cupti_shared_library", "cupti", "cupti_static", "checkpoint_shared_library", "checkpoint", "nvperf_host_shared_library", "nvperf_host", "nvperf_target_shared_library", "nvperf_target", "pcsamplingutil_shared_library", "pcsamplingutil", "header_list", "headers", "cuda_cupti", "shared_library_files"],
    "cuda_curand": ["curand_shared_library", "curand", "curand_static", "header_list", "headers", "shared_library_files"],
    "cuda_cusolver": ["cusolver_shared_library", "cusolver", "cusolverMg_shared_library", "cusolverMg", "cusolver_static", "cusolver_lapack_static", "cusolver_metis_static", "metis_static", "header_list", "headers", "shared_library_files"],
    "cuda_cusparse": ["cusparse_shared_library", "cusparse", "cusparse_static", "header_list", "headers", "shared_library_files"],
    "cuda_driver": [
        "driver_shared_library",
        "nvidia-ptxjitcompiler_shared_library",
        "cuda_shared_library",
        "nvidia_driver",
        "nvidia_ptxjitcompiler",
        "cudadebugger_shared_library",
        "nvidia_nvvm_shared_library",
        "include_cuda_umd_libs",
        "cuda_umd_libs",
        "shared_library_files",
    ],
    "cuda_nvcc": ["nvcc_directory", "libdevice", "nvlink", "fatbinary", "bin2c", "ptxas", "nvcc", "cudafe", "nvcc_profile", "prelink_stub", "nvcc_device_query", "bin", "link_stub", "header_list", "headers", "cuda_nvcc", "nvptxcompiler"],
    "cuda_nvdisasm": ["nvdisasm"],
    "cuda_nvjitlink": ["nvjitlink_shared_library", "nvjitlink", "nvjitlink_static", "header_list", "headers", "shared_library_files"],
    "cuda_nvml": ["header_list", "headers", "nvidia-ml_stub", "nvidia_ml_static_stub", "nvml"],
    "cuda_nvptxcompiler": ["header_list", "headers", "nvptxcompiler_static", "nvptxcompiler"],
    "cuda_nvprune": ["nvprune"],
    "cuda_nvrtc": ["nvrtc_main", "nvrtc_builtins", "nvrtc", "nvrtc_static", "nvrtc_builtins_static", "nvrtc_stub", "header_list", "headers", "shared_library_files"],
    "cuda_nvtx": ["header_list", "headers", "shared_library_files"],
    "cuda_nvvm": ["cicc", "libdevice", "libnvvm", "nvptxcompiler"],
    "cuda_profiler_api": ["header_list", "headers"],
}
